### ISSUE TITLE
Add libraries for DOM storage

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/storage-on-the-web#4]
@nolanlawson do you have a preferred top 3-4? 

Some references:
https://github.com/marcuswestin/store.js
https://github.com/brianleroux/lawnchair
https://github.com/tsironis/lockr
https://github.com/pamelafox/lscache

**Comment by nolanlawson** [comment]
I'm enormously biased, but I would typically recommend against any library that relies on LocalStorage alone since it's synchronous, has a low quota, is unavailable in a worker, etc. As for the listed libraries above, I've only used Lawnchair, which I think was more useful back in the early days of IndexedDB when Google Gears was still something to contend with. :)

When giving advice on choosing a DB, I usually tell people:
- localForage for 90% of use cases, simple key-value stuff
- Dexie if you want complex queries or secondary indexes
- PouchDB if you want sync
- Lovefield if you want relational
- YDN-DB if you want something Dexie-like that also works with WebSQL

There's also LokiJS which is interesting in that it's in-memory and just periodically writes to disk, so it can lose data but is very fast apparently.

**Comment by addyosmani** [comment]
@nolanlawson Thanks for the input! 🔥 

After taking a look at the latest IDB libraries by Jake, I've tried to incorporate your suggestions above (which I agree with) with some brief differenciations between the most useful abstractions in the IDB column. On LocalStorage, I've referenced two libraries for now (I know, ew), but want to emphasize as much as possible the overarching theme of IDB + the Cache API being the way to go for anything modern.

I've also introduced a future work section (capturing what the open-web storage team in Chrome are currently looking at - more than happy to add anything you know MS or FF are doing here) and a resources section that is basically just stuff you've published 🚀 (seriously, your tools and research have been so helpful to the storage community).

If there's anything else you feel is worth a mention, please feel free to shout out!
